services:
  - type: web
    name: pomodoro-app
    env: python
    buildCommand: "./build.sh && pip install -r requirements.txt"
    startCommand: "./prestart.sh && gunicorn app:app --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production 